/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    themes: Theme;
    bibliography: Bibliography;
    pages: Page;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    bibliography: BibliographySelect<false> | BibliographySelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Numéro de série du carnet — affiché « n° 042 » côté lecteur. Manuel et stable.
   */
  numero: number;
  title: string;
  /**
   * URL-safe, ex : 'homonationalisme-diplomatie'. Sert à la route /billets/<slug>/.
   */
  slug: string;
  type: 'analyse' | 'note' | 'fiche';
  /**
   * Taxonomie multivaluée — un billet peut appartenir à plusieurs thèmes.
   */
  themes?: (number | Theme)[] | null;
  publishedAt: string;
  /**
   * ~2-3 phrases — affichées en deck sous le titre.
   */
  lede: string;
  /**
   * Lexical — slash menu pour insérer des notes, citations longues, références biblio, figures.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Références listées en pied du billet, dans l’ordre choisi ici. Cliquables depuis les biblio_inline du corps.
   */
  bibliography?: (number | Bibliography)[] | null;
  /**
   * Calculé automatiquement depuis le corps au save.
   */
  readingTime?: number | null;
  /**
   * Identifiant stable, dérivé de l’année et du numéro (ex : carnet:2026-042).
   */
  idCarnet?: string | null;
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  /**
   * Ex : « Genre & géopolitique », « Queer theory », « Migrations & exil ».
   */
  name: string;
  /**
   * Identifiant URL, ex : 'genre-geopolitique'. Sert aussi de hash de tag inline (#queer-theory).
   */
  slug: string;
  /**
   * 1 à 2 phrases — apparaît en hero de la page /theme/<slug>/.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bibliography".
 */
export interface Bibliography {
  id: number;
  /**
   * Clé courte, ex : 'farris-2017'. Sert d'ancre `#bib-...` côté article.
   */
  slug: string;
  type: 'book' | 'chapter' | 'article' | 'paper' | 'web' | 'other';
  /**
   * Format Chicago : « Nom, Prénom » ; plusieurs auteurs séparés par « ; ».
   */
  author: string;
  year: number;
  title: string;
  /**
   * Pour les livres : éditeur. Pour les articles : revue.
   */
  publisher?: string | null;
  place?: string | null;
  volume?: string | null;
  /**
   * Optionnel — collection éditoriale, série, etc.
   */
  journal?: string | null;
  /**
   * Ex : « 43-82 », « chap. 3 ».
   */
  pages?: string | null;
  url?: string | null;
  doi?: string | null;
  /**
   * Optionnel — note de lecture, raison de l'inclusion, mémo de contexte. Non publié.
   */
  annotation?: string | null;
  displayLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-safe, ex : 'about', 'colophon', 'mentions-legales'. Sert de match de route Astro.
   */
  slug: string;
  /**
   * ~150 caractères, affichée dans Google.
   */
  description?: string | null;
  /**
   * Si coché, demande aux moteurs de ne pas indexer.
   */
  noindex?: boolean | null;
  /**
   * Ex : « À propos », « Colophon ». Apparaît au-dessus du titre, en accent.
   */
  eyebrow?: string | null;
  /**
   * 1 phrase, affichée en gros sous le titre.
   */
  lede?: string | null;
  /**
   * Compose la page en empilant des sections (Prose, Figure, Citation).
   */
  sections?:
    | (
        | {
            /**
             * Apparaît en h2 si présent. Laisser vide pour pas de titre.
             */
            titre?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'prose';
          }
        | {
            image: number | Media;
            legende?: string | null;
            /**
             * Ex : « Photo : Alice Aussel Delamaide, Bangui, 2017 » ou « © UN Photo / Eskinder Debebe ».
             */
            credit?: string | null;
            align?: ('left' | 'center' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'figure';
          }
        | {
            text: string;
            /**
             * Ex : « Puar (2007), p. 23 ». Affichée en petits caractères mutés.
             */
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'citation_bloc';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  /**
   * Root = compte propriétaire (1 seul, non supprimable). Admin = peut gérer les comptes. Éditeur·ice = édite le contenu.
   */
  role: 'root' | 'admin' | 'editor';
  /**
   * Géré automatiquement par le système d'invitation.
   */
  status: 'pending' | 'active' | 'disabled';
  invitation?: {
    tokenHash?: string | null;
    expiresAt?: string | null;
    invitedBy?: (number | null) | User;
    invitedAt?: string | null;
  };
  twoFactor?: {
    emailCodeHash?: string | null;
    emailCodeExpiresAt?: string | null;
    emailCodeAttempts?: number | null;
  };
  lastActivityAt?: string | null;
  lastLoginAt?: string | null;
  trustedDevices?:
    | {
        deviceId: string;
        fingerprintHash: string;
        label?: string | null;
        userAgent?: string | null;
        ip?: string | null;
        createdAt: string;
        expiresAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'bibliography';
        value: number | Bibliography;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  numero?: T;
  title?: T;
  slug?: T;
  type?: T;
  themes?: T;
  publishedAt?: T;
  lede?: T;
  body?: T;
  bibliography?: T;
  readingTime?: T;
  idCarnet?: T;
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bibliography_select".
 */
export interface BibliographySelect<T extends boolean = true> {
  slug?: T;
  type?: T;
  author?: T;
  year?: T;
  title?: T;
  publisher?: T;
  place?: T;
  volume?: T;
  journal?: T;
  pages?: T;
  url?: T;
  doi?: T;
  annotation?: T;
  displayLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  noindex?: T;
  eyebrow?: T;
  lede?: T;
  sections?:
    | T
    | {
        prose?:
          | T
          | {
              titre?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        figure?:
          | T
          | {
              image?: T;
              legende?: T;
              credit?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        citation_bloc?:
          | T
          | {
              text?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  status?: T;
  invitation?:
    | T
    | {
        tokenHash?: T;
        expiresAt?: T;
        invitedBy?: T;
        invitedAt?: T;
      };
  twoFactor?:
    | T
    | {
        emailCodeHash?: T;
        emailCodeExpiresAt?: T;
        emailCodeAttempts?: T;
      };
  lastActivityAt?: T;
  lastLoginAt?: T;
  trustedDevices?:
    | T
    | {
        deviceId?: T;
        fingerprintHash?: T;
        label?: T;
        userAgent?: T;
        ip?: T;
        createdAt?: T;
        expiresAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  /**
   * Affichée dans le footer (col 1).
   */
  baseline?: string | null;
  /**
   * Footer (col 1, sous la baseline, en mono).
   */
  copyrightLine?: string | null;
  social?: {
    /**
     * URL complète du profil Mastodon.
     */
    mastodon?: string | null;
    /**
     * URL complète du profil Bluesky.
     */
    bluesky?: string | null;
    /**
     * URL complète du profil ORCID.
     */
    orcid?: string | null;
    /**
     * URL complète de la page HAL.
     */
    hal?: string | null;
  };
  navFooter?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  baseline?: T;
  copyrightLine?: T;
  social?:
    | T
    | {
        mastodon?: T;
        bluesky?: T;
        orcid?: T;
        hal?: T;
      };
  navFooter?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}